site_name: coola
site_url: 'https://durandtibo.github.io/coola/'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.code.select
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: overrides

nav:
  - Home: index.md
  - get_started.md
  - User Guide:
      - uguide/quickstart.md
      - uguide/types.md
      - uguide/recursive.md
      - uguide/iterator.md
      - uguide/registry.md
      - uguide/random.md
      - uguide/customization.md
      - uguide/examples.md
  - Developer Guide:
      - dev/development.md
      - dev/architecture.md
  - Upgrade Guide:
      - upgrade/0.3.md
      - upgrade/0.4.md
  - Reference:
      - refs/index.md
      - refs/equality.md
      - refs/iterator.md
      - refs/random.md
      - refs/recursive.md
      - refs/registry.md
      - refs/reducers.md
      - refs/summary.md
      - refs/testers.md
      - refs/utils.md
  - GitHub: https://github.com/durandtibo/coola

repo_url: https://github.com/durandtibo/coola
repo_name: durandtibo/coola

markdown_extensions:
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ ../src ]
          options:
            allow_inspection: true
            docstring_style: google
            separate_signature: true
            show_bases: true
            show_object_full_path: true
            show_root_full_path: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature: true
            show_signature_annotations: true
            show_source: false
            signature_crossrefs: true

extra:
  version:
    method: mike

copyright: Copyright &copy; 2022 - present Thibaut Durand
